#!/bin/bash

#SBATCH --partition=gpu_mig
#SBATCH --gpus=1
#SBATCH --job-name=SciBERT_encoding
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH --time=04:00:00
#SBATCH --output=slurm_output_%A.out

module purge
module load 2023
module load PyTorch/2.1.2-foss-2023a-CUDA-12.1.1

# Your job starts in the directory where you call sbatch
cd $HOME/MLFPA/MLFPA_project/
# Activate your environment
source ./
# Run your code
srun python -u scibert.py